export const USER_LOGIN = 'USER_LOGIN'
export const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS'

export const SET_USER_LOCATION = 'SET_USER_LOCATION'
export const SET_USER_LOCATION_SUCCESS = 'SET_USER_LOCATION_SUCCESS'
export const SET_USER_LOCATION_ERROR = 'SET_USER_LOCATION_ERROR'

export const SUBMIT_REPORT = 'SUBMIT_REPORT'
export const SUBMIT_REPORT_SUCCES = 'SUBMIT_REPORT_SUCCESS'
export const SUBMIT_REPORT_ERROR = 'SUBMIT_REPORT_ERROR'

export const DISMISS_MODAL = 'DISMISS_MODAL'
export const SELECT_MESSAGE = 'SELECT_MESSAGE'
export const SET_IMAGE_URL = 'SET_IMAGE_URL'
export const SET_LOADING_STATE = 'SET_LOADING_STATE'
